version: '3.2'

volumes:
  tmp-data: {}

services:
  app: &app
    image: zunme/lara-road:1.1
    user: "${APP_UID:-10001}:${APP_GID:-10001}"
    dns:
        - 8.8.8.8
        - 8.8.8.7
    environment:
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
      HOME: /tmp
      APP_DEBUG: 'true'
      APP_ENV: local
      REDIS_HOST: 150.230.252.144
      REDIS_PASSWORD:
      DB_HOST: 150.230.252.144
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - tmp-data:/tmp:rw
      - .:/app:rw

  web:
    <<: *app
    command: rr serve -c .rr.local.yaml
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q "http://127.0.0.1:8082/health?plugin=http&plugin=rpc"']
      interval: 2s
      timeout: 2s

  queue:
    <<: *app
    command: php /app/artisan queue:work --memory=256 --sleep=1

  cron:
    <<: *app
    command: supercronic /etc/supercronic/laravel # it runs artisan schedule:run
                       
