version: '2.3'

services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./storage_database/conf.d:/etc/mysql/conf.d
      - ./storage_database/lib:/var/lib/mysql
      - ./storage_database/initdb.d:/docker-entrypoint-initdb.d
      - ./storage_database/data:/data

    mem_limit: 512m
    networks:
      - mysqlnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - TZ=Asia/Seoul

  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mariadb-phpmyadmin
    ports:
      - "8001:80"
    mem_limit: 512m
    networks:
      - mysqlnetwork
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
        #- vm.overcommit_memory=1
    ports:
      - "6380:6379"
    volumes:
      - ./storage_database/redis:/data
    mem_limit: 96m
    networks:
      - mysqlnetwork
volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  mysqlnetwork:
    driver: bridge
